# Generated by Django 4.2.6 on 2023-10-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_secription_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vreated_at',
            new_name='created_at',
        ),
    ]
